### ISSUE TITLE
docs: update suggestion to use deprecated recorder project

### ISSUE THREAD

**Issue by dijitali** [checkly/docs.checklyhq.com#858]
### What is the improvement or update you wish to see?

[Using script recorders](https://www.checklyhq.com/learn/headless/script-recorders/) page still links to your deprecated project: https://github.com/checkly/headless-recorder.

Might be good to link to Playwright Codegen instead as the current recommended tool: https://playwright.dev/docs/codegen

### Is there any context that might help us understand?

N/A, see above

### Does the docs page already exist? Please link to it.

https://www.checklyhq.com/learn/headless/script-recorders/

**Comment by stefanjudis** [comment]
@dijitali that's right. Let me fix that right away!

Thanks for the nudge!

**Comment by stefanjudis** [comment]
@dijitali Thanks for reporting, I updated and deployed the page just now! 💪
